modLoader="javafml"
loaderVersion="[36,)"
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/HeizerMods/RelivedMobs/issues"

[[mods]]
	modId="relivedmobs"
	version="${file.jarVersion}"
	displayName="Relived Mobs"
	authors="All stuff in discord server and Heizer!"
	description='''This Mod is focusing in spice up the Vanilla World, 
		by adding new Mobs, real ones like Birds and Fishes, but also fantasy ones like raptors, 
		a terracotta mecha Golem or a Wood beast similar to a angry bear. 
		Also new Dungeons and other Structures, new mechanics, new Vegetation like Flowers and bushes for example. 
		Also much more stuff and plans are coming in the future! So stay tuned! :3
	'''

[[dependencies.relivedmobs]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.relivedmobs]]
    modId="minecraft"
    mandatory=true
	versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"	